---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library("dplyr")
library("tidyverse")
library(readr)
```

```{r}
Communication_score <- read_csv("d:/Documents/GitHub/IntroDSproject/Scored data+Rmds/Communication_score.csv")
Education_score <- read_csv("d:/Documents/GitHub/IntroDSproject/Scored data+Rmds/Education_score.csv")
Emissions_score <- read_csv("d:/Documents/GitHub/IntroDSproject/Scored data+Rmds/Emissions_score.csv")
Employment_score <- read_csv("d:/Documents/GitHub/IntroDSproject/Scored data+Rmds/Employment_score.csv")
Energy_score <- read_csv("d:/Documents/GitHub/IntroDSproject/Scored data+Rmds/Energy_score.csv")
Environment_score <- read_csv("d:/Documents/GitHub/IntroDSproject/Scored data+Rmds/Environment_score.csv")
FoodDeficit_score <- read_csv("d:/Documents/GitHub/IntroDSproject/Scored data+Rmds/FoodDeficit_score.csv")
Gender_score <- read_csv("d:/Documents/GitHub/IntroDSproject/Scored data+Rmds/Gender_score.csv")
Population_score <- read_csv("d:/Documents/GitHub/IntroDSproject/Scored data+Rmds/Population_score.csv")
Security_score <- read_csv("d:/Documents/GitHub/IntroDSproject/Scored data+Rmds/Security_score.csv")
Tourism_score <- read_csv("d:/Documents/GitHub/IntroDSproject/Scored data+Rmds/Tourism_score.csv")
GDP_score <- read_csv("d:/Documents/GitHub/IntroDSproject/Scored data+Rmds/GDP_score.csv")
childwelfare_score <- read_csv("d:/Documents/GitHub/IntroDSproject/Scored data+Rmds/childwelfare_score.csv")
diversity_score <- read_csv("d:/Documents/GitHub/IntroDSproject/Scored data+Rmds/diversity_score.csv")
happyplanet_score <- read_csv("d:/Documents/GitHub/IntroDSproject/Scored data+Rmds/happyplanet_score.csv")
```



```{r}
final_score_table <- Communication_score %>%
    full_join(Education_score, by='CountryName') %>%
    full_join(Emissions_score, by='CountryName') %>%
  full_join(Environment_score, by='CountryName') %>%
  full_join(FoodDeficit_score, by='CountryName') %>%
  full_join(Gender_score, by='CountryName') %>%
  full_join(Population_score, by='CountryName') %>%
  full_join(Employment_score, by='CountryName') %>%
  full_join(Energy_score, by='CountryName') %>%
  full_join(Security_score, by='CountryName') %>%
  full_join(Tourism_score, by='CountryName') %>%
  full_join(GDP_score, by='CountryName') %>%
  full_join(childwelfare_score, by='CountryName')%>%
  full_join(diversity_score, by='CountryName')%>%
  full_join(happyplanet_score, by='CountryName')

write.csv(final_score_table, file = "final_score_table.csv")
```

