---
title: "ethnic frac"
author: "Shravanthi Seshasayee"
date: "9 December 2017"
output: html_document
---

```{r setup, include=FALSE}
library(rvest)
library(dplyr)
library(tidyverse)

```

```{r}
url <- "https://en.wikipedia.org/wiki/List_of_countries_ranked_by_ethnic_and_cultural_diversity_level"
pop <- read_csv("/IntroDSproject/WDI data split/Population.csv")
h <- read_html(url)
efindex <- h %>% html_nodes("table") %>% html_table(fill = TRUE) %>%
        .[[3]]

View(efindex)
migstock <- select(pop, "CountryName", "Year", "SM.POP.TOTL.ZS")
#crime[crime == 0] <- NA
migstock <- migstock[order(-migstock$Year),]
migstock <- na.omit(migstock)
migstock <- migstock %>% distinct(CountryName, .keep_all = TRUE)
migstock <- mutate(migstock, rank.migstock = as.numeric(as.factor(rank(-(SM.POP.TOTL.ZS)))))

ef.rank <- select(efindex, "Country", "Ethnic Diversity Rank")
colnames(ef.rank)[1] <- "CountryName"

diversity <- left_join(migstock, ef.rank, by = "CountryName")
diversity <- select(diversity, "CountryName", "", "rank.legal", "VC.IHR.PSRC.P5", "rank.homi")
diversity <- mutate(diversity, country.score = as.numeric(as.factor(rank(((rank.legal+rank.homi)/2)))))
View(diversity)

```


```{r}
tab <- tab %>% setNames(c("state", "population", "total", "murder_rate"))
head(tab)
```

