---
title: "Economy_Ranking"
author: "Seranne Motilal, Shravanthi Seshasayee and Sanjana Sunderesan"
date: "3 December 2017"
output: html_document
---
```{r}
library(tidyverse)
```

```{r}
economy <- read_csv("F://IntroDSproject/WDI data split/Economy.csv")

#IC.LGL.CRED.XQ - Available for 2015, 2014
#IC.FRM.FEMM.ZS - Not enough data - Removed
#GC.XPN.COMP.ZS - Not enough data - Removed
#IC.FRM.CRIM.ZS - Available for 2010, 2011, 2012 - Too few, and inaccurate reporting - Removed
#FP.CPI.TOTL.ZG - Available for 2014 and earlier
```

```{r}
totl <- select(economy, "CountryName", "Year", "FP.CPI.TOTL.ZG")
totl <- totl[order(-totl$Year),]
totl <- na.omit(totl)
totl <- totl %>% distinct(CountryName, .keep_all = TRUE)
totl <- mutate(totl, rank.totl = rank(totl$FP.CPI.TOTL.ZG))
View(totl)

crime <- select(economy, "CountryName", "Year", "IC.FRM.CRIM.ZS")
crime[crime == 0] <- NA
crime <- crime[order(-crime$Year),]
crime <- na.omit(crime)
crime <- crime %>% distinct(CountryName, .keep_all = TRUE)
crime <- mutate(crime, rank.crime = rank(IC.FRM.CRIM.ZS))
View(crime)

cred <- select(economy, "CountryName", "Year", "IC.LGL.CRED.XQ")
#crime[crime == 0] <- NA
cred <- cred[order(-cred$Year),]
cred <- na.omit(cred)
cred <- cred %>% distinct(CountryName, .keep_all = TRUE)
View(cred)
cred <- mutate(cred, rank.cred = rank(IC.LGL.CRED.XQ))
View(cred)
```

```{r}
economy <- merge(x = economy, y = totl, all.x = TRUE)
economy <- merge(x = economy, y = crime, all.x = TRUE)
economy <- merge(x = economy, y = cred, all.x = TRUE)
View(economy)
economy <- economy %>% mutate(economy.rank = (economy$rank.totl + economy$rank.crime + economy$rank.cred)/3)
View(economy)
```

