---
title: "Discard Code"
author: "Seranne Motilal, Shravanthi Seshasayee, Sanjana Sunderesan"
date: "3 December 2017"
output: html_document
---

```{r}
#International migrant stock

migstock <- select(pop, "CountryName", "Year", "SM.POP.TOTL.ZS")
#crime[crime == 0] <- NA
migstock <- migstock[order(-migstock$Year),]
migstock <- na.omit(migstock)
migstock <- migstock %>% distinct(CountryName, .keep_all = TRUE)
migstock <- mutate(migstock, rank.migstock = as.numeric(as.factor(rank(-(SM.POP.TOTL.ZS)))))

```

```{r}
#Children in employment, unpaid family workers
chldlabour <- select(chld, "CountryName", "Year", "SL.FAM.0714.ZS")
crime[crime == 0] <- NA
chldlabour <- chldlabour[order(-chldlabour$Year),]
chldlabour <- na.omit(chldlabour)
chldlabour <- chldlabour %>% distinct(CountryName, .keep_all = TRUE)
chldlabour <- mutate(chldlabour, rank.chldlabour = as.numeric(as.factor(rank(-(IC.LGL.CRED.XQ)))))
View(chldlabour)

```

```{r}
wdi <- read.csv("F://IntroDSProject/ourWDI.csv")

wdi$Year <- as.factor(wdi$Year)
levels(wdi$Year)

MobCelSub <- data.frame("Country" = wdi$CountryName[wdi$IndicatorCode == "IT.CEL.SETS.P2"], "Year" = wdi$Year[wdi$IndicatorCode == "IT.CEL.SETS.P2"] | wdi$Year, "CellPerCap" = wdi$Value[wdi$IndicatorCode == "IT.CEL.SETS.P2"])

internet <- data.frame("Country" = wdi$CountryName[wdi$IndicatorCode == "IT.NET.USER.P2"], "Year" = wdi$Year[wdi$IndicatorCode == "IT.NET.USER.P2"] "InternetPerCap" = wdi$Value[wdi$IndicatorCode == "IT.NET.USER.P2"])

View(MobCelSub)
View(internet)

comm <- merge(MobCelSub, internet, by = "Country", all.x = TRUE, all.y = FALSE)
View(comm)


#a <- data.frame()

View(Comm)
#View(a)

#Country = data.frame(wdi$CountryName)
#comm <- merge(Country, df2, by=”common_key_column”, all.x=TRUE)
```
