---
title: "energy"
output: html_document
---

```{r}
library(readr)
library(tidyverse)
library(dplyr)
library(ggplot2)
```

```{r}
Energy <- read_csv("d:/Documents/GitHub/IntroDSproject/WDI data split/Energy.csv")
 Energy1<- select(Energy, "CountryName", "CountryCode", "Year", "EG.ELC.ACCS.ZS")
 Energy1 <- Energy1[order(-Energy1$Year),]
 Energy1<- na.omit(Energy1)
 Energy1 <- Energy1%>% distinct(CountryName, .keep_all = TRUE)
 Energy1 <- Energy1 %>% mutate(finalrank_eng1 = rank(-Energy1$EG.ELC.ACCS.ZS))
 Energy1$finalrank_eng1<- as.numeric(as.factor(Energy1$finalrank_eng1))
 
 Energy2<- select(Energy, "CountryName", "CountryCode", "Year", "EG.FEC.RNEW.ZS")
 Energy2 <- Energy2[order(-Energy2$Year),]
 Energy2<- na.omit(Energy2)
 Energy2 <- Energy2%>% distinct(CountryName, .keep_all = TRUE)
 Energy2 <- Energy2 %>% mutate(finalrank_eng2 = rank(Energy2$EG.FEC.RNEW.ZS))
 Energy2$finalrank_eng2<- as.numeric(as.factor(Energy2$finalrank_eng2))
 
 Energy3<- select(Energy, "CountryName", "CountryCode", "Year", "EG.USE.COMM.FO.ZS")
 Energy3 <- Energy3[order(-Energy3$Year),]
 Energy3<- na.omit(Energy3)
 Energy3 <- Energy3%>% distinct(CountryName, .keep_all = TRUE)
 Energy3 <- Energy3 %>% mutate(finalrank_eng3 = rank(Energy3$EG.USE.COMM.FO.ZS))
 Energy3$finalrank_eng3<- as.numeric(as.factor(Energy3$finalrank_eng3))
 
 Enjoin <- left_join(Energy1, Energy2, "CountryName")
 Energy<- left_join(Enjoin, Energy3, "CountryName")
 Energy<- select(Energy,"CountryName", "finalrank_eng1", "finalrank_eng2", "finalrank_eng3")
 
 Energy <- Energy[rowSums(is.na(Energy)) < 2, ]
 i <- which(is.na(Energy), arr.ind = TRUE)
 Energy[i] <- rowMeans(Energy[,-1], na.rm = TRUE)[i[,1]]
 
 Energy<- Energy %>% mutate(score_eng = (finalrank_eng1 + finalrank_eng2 + finalrank_eng3)/3)
 Energy <- Energy %>% mutate(finalrank_eng = rank(Energy$score_eng))
 
 write.csv(Energy, file = "Energy_score.csv")
```

