---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library("dplyr")
library("tidyverse")
library("readr")

```

#Gather all the variable indices join to create on table 

```{r}
Communication_score <- read_csv("../Scored data+Rmds/Communication_score.csv")
Education_score <- read_csv("../Scored data+Rmds/Education_score.csv")
Emissions_score <- read_csv("../Scored data+Rmds/Emissions_score.csv")
Employment_score <- read_csv("../Scored data+Rmds/Employment_score.csv")
Energy_score <- read_csv("../Scored data+Rmds/Energy_score.csv")
Environment_score <- read_csv("../Scored data+Rmds/Environment_score.csv")
FoodDeficit_score <- read_csv("../Scored data+Rmds/FoodDeficit_score.csv")
Gender_score <- read_csv("../Scored data+Rmds/Gender_score.csv")
Population_score <- read_csv("../Scored data+Rmds/Population_score.csv")
Security_score <- read_csv("../Scored data+Rmds/Security_score.csv")
Tourism_score <- read_csv("../Scored data+Rmds/Tourism_score.csv")
GDP_score <- read_csv("../Scored data+Rmds/GDP_score.csv")
childwelfare_score <- read_csv("../Scored data+Rmds/childwelfare_score.csv")
diversity_score <- read_csv("../Scored data+Rmds/diversity_score.csv")
happyplanet_score <- read_csv("../Scored data+Rmds/happyplanet_score.csv")
Negative_Affect <- read_csv("../Scored data+Rmds/Negative Affect.csv")
Positive_Affect <- read_csv("../Scored data+Rmds/Positive Affect.csv")
```


```{r}
final_score_table <- Communication_score %>%
    full_join(Education_score, by='CountryName') %>%
    full_join(Emissions_score, by='CountryName') %>%
  full_join(Environment_score, by='CountryName') %>%
  full_join(FoodDeficit_score, by='CountryName') %>%
  full_join(Gender_score, by='CountryName') %>%
  full_join(Population_score, by='CountryName') %>%
  full_join(Employment_score, by='CountryName') %>%
  full_join(Energy_score, by='CountryName') %>%
  full_join(Security_score, by='CountryName') %>%
  full_join(Tourism_score, by='CountryName') %>%
  full_join(GDP_score, by='CountryName') %>%
  full_join(childwelfare_score, by='CountryName')%>%
  full_join(diversity_score, by='CountryName')%>%
  full_join(happyplanet_score, by='CountryName')%>%
  full_join(Negative_Affect, by='CountryName')%>%
  full_join(Positive_Affect, by='CountryName')
```

# This contains the columns with only the required final ranks for each variable
```{r}
final_score <- final_score_table %>% select(CountryName,
                                            finalscore_child,
                                            finalrank_comm,
                                            finalrank_diversity,
                                            finalrank_edu,
                                            finalrank_emission,
                                            finalrank_empl,
                                            finalrank_eng,
                                            finalrank_env,
                                            finalrank_deficit,
                                            finalrank_gen,
                                            finalrank_GDP,
                                            finalrank_pop,
                                            finalscore_security,
                                            finalrank_tourism,
                                            finalrank_hpi,
                                            finalrank_neg,
                                            finalrank_pos)
```






#drop countries with too many NA's and use of mean of the coutries other ranking to fill in NA'for remaining countries

```{r}
 #final_score <- final_score[order(-final_score$Year),]
 final_score[rowSums(is.na(final_score)) < ncol(final_score)/2, ]
 final_score<- aggregate(x=final_score[c("finalscore_child",
                                            "finalrank_comm",
                                            "finalrank_diversity",
                                            "finalrank_edu",
                                            "finalrank_emission",
                                            "finalrank_empl",
                                            "finalrank_eng",
                                            "finalrank_env",
                                            "finalrank_deficit",
                                            "finalrank_gen",
                                            "finalrank_GDP",
                                            "finalrank_pop",
                                            "finalscore_security",
                                            "finalrank_tourism",
                                            "finalrank_hpi",
                                            "finalrank_neg",
                                            "finalrank_pos")], by=list(name=final_score$CountryName), FUN = "mean" , na.rm = TRUE)
 colnames(final_score)[1] <- "CountryName"
  #final_score[rowSums(is.na(final_score1)) < ncol(final_score)/3, ]
 #final_score <- final_score%>% distinct(CountryName, .keep_all = TRUE)
 final_score <- final_score[rowSums(is.na(final_score)) < 8, ]
 
 i <- which(is.na(final_score), arr.ind = TRUE)
 final_score[i] <- rowMeans(final_score[,2:18], na.rm = TRUE)[i[,1]]
 
final_score<- final_score %>% 
   mutate(ourindex = (finalscore_child + 
                        finalrank_comm + 
                        finalrank_diversity + 
                        finalrank_edu + 
                        finalrank_emission + 
                        finalrank_empl + 
                        finalrank_eng + 
                        finalrank_env + 
                        finalrank_deficit + 
                        finalrank_gen + 
                        finalrank_GDP + 
                        finalrank_pop + 
                        finalscore_security + 
                        finalrank_tourism + 
                        finalrank_hpi + 
                        finalrank_neg + 
                        finalrank_pos)/17) %>% 
  mutate(finalindex = rank(ourindex))

#fill in regional data

url <- "https://raw.githubusercontent.com/lukes/ISO-3166-Countries-with-Regional-Codes/master/all/all.csv"

regions <-read.csv(url)
regions <- regions %>% select(name, region, sub.region)
colnames(regions)[1] <- "CountryName"
final_score <- left_join(final_score, regions, "CountryName")
write.csv(final_score, file = "CalculatedOurindex.csv")
```

# Fixing Regions
```{r}
read.csv("/IntroDSproject/Final score data/CalculatedOurindex.csv")
levels(CalculatedOurindex$CountryName)[levels(CalculatedOurindex$CountryName) == "Egypt, Arab Rep."] <- "Egypt"
levels(CalculatedOurindex$CountryName)[levels(CalculatedOurindex$CountryName) == "Lao PDR"] <- "Laos"

CalculatedOurindex$sub.region[CalculatedOurindex$CountryName == "Bolivia" & is.na(CalculatedOurindex$sub.region)] <- "South America"

CalculatedOurindex$sub.region[CalculatedOurindex$CountryName == "Egypt" & is.na(CalculatedOurindex$sub.region)] <- "Northern Africa"

CalculatedOurindex$sub.region[CalculatedOurindex$CountryName == "Caribbean small states" & is.na(CalculatedOurindex$sub.region)] <- "South America"

CalculatedOurindex$sub.region[CalculatedOurindex$CountryName == "Venezuela" & is.na(CalculatedOurindex$sub.region)] <- "South America"

CalculatedOurindex$sub.region[CalculatedOurindex$CountryName == "Cote d'Ivoire" & is.na(CalculatedOurindex$sub.region)] <- "Western Africa"

CalculatedOurindex$sub.region[CalculatedOurindex$CountryName == "Democratic Republic of Congo" & is.na(CalculatedOurindex$sub.region)] <- "Middle Africa"

CalculatedOurindex$sub.region[CalculatedOurindex$CountryName == "Tanzania" & is.na(CalculatedOurindex$sub.region)] <- "Middle Africa"

CalculatedOurindex$sub.region[CalculatedOurindex$CountryName == "Republic of Congo" & is.na(CalculatedOurindex$sub.region)] <- "Western Africa"

CalculatedOurindex$sub.region[CalculatedOurindex$CountryName == "Iran" & is.na(CalculatedOurindex$sub.region)] <- "Western Asia"

CalculatedOurindex$sub.region[CalculatedOurindex$CountryName == "Laos" & is.na(CalculatedOurindex$sub.region)] <- "South-Eastern Asia"

CalculatedOurindex$sub.region[CalculatedOurindex$CountryName == "Macedonia" & is.na(CalculatedOurindex$sub.region)] <- "Southern Europe"

CalculatedOurindex$sub.region[CalculatedOurindex$CountryName == "Moldova" & is.na(CalculatedOurindex$sub.region)] <- "Eastern Europe"

CalculatedOurindex$sub.region[CalculatedOurindex$CountryName == "Russia" & is.na(CalculatedOurindex$sub.region)] <- "Eastern Europe"

CalculatedOurindex$sub.region[CalculatedOurindex$CountryName == "United Kingdom" & is.na(CalculatedOurindex$sub.region)] <- "Western Europe"

CalculatedOurindex$sub.region[CalculatedOurindex$CountryName == "South Korea" & is.na(CalculatedOurindex$sub.region)] <- "South-Eastern Asia"

CalculatedOurindex$sub.region[CalculatedOurindex$CountryName == "Vietnam" & is.na(CalculatedOurindex$sub.region)] <- "South-Eastern Asia"

CalculatedOurindex$sub.region[CalculatedOurindex$CountryName == "Syria" & is.na(CalculatedOurindex$sub.region)] <- "Western Asia"

CalculatedOurindex$region[CalculatedOurindex$sub.region == "South America" & is.na(CalculatedOurindex$region)] <- "Americas"

CalculatedOurindex$region[(CalculatedOurindex$sub.region == "Western Africa" | CalculatedOurindex$sub.region == "Middle Africa" | CalculatedOurindex$sub.region == "Northern Africa")  & is.na(CalculatedOurindex$region)] <- "Africa"

CalculatedOurindex$region[(CalculatedOurindex$sub.region == "Western Asia" | CalculatedOurindex$sub.region == "South-Eastern Asia")  & is.na(CalculatedOurindex$region)] <- "Asia"

CalculatedOurindex$region[(CalculatedOurindex$sub.region == "Western Europe" | CalculatedOurindex$sub.region == "Eastern Europe" | CalculatedOurindex$sub.region == "Southern Europe")  & is.na(CalculatedOurindex$region)] <- "Europe"

#CalculatedOurindex <- CalculatedOurindex[rowSums(is.na(CalculatedOurindex)) > 0,]

write.csv(CalculatedOurindex, file = "CalculatedOurindex.csv")

```

