---
title: "World plot"
output: html_document
---
```{r}
library(rworldmap)
library(ggplot2)
library(gridExtra)
library(dplyr)
library(tidyverse)
library(maps)
library(ggthemes)
library(forcats)
```

#WHR happiness index

```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}
url <- "https://raw.githubusercontent.com/Seranne/IntroDSproject/master/Source%20Data/World%20Happiness%20Report/2016.csv"
whr <- read_csv(url)

par(mai=c(0,0,0.2,0),xaxs="i",yaxs="i")

#joining the data to a map
whrplot<- joinCountryData2Map(whr, 
                              joinCode = "NAME", 
                              nameJoinColumn = "Country")

#creating a user defined colour palette
op <- palette(c('green', 'yellow','red'))

#find quartile breaks
cutVector <- quantile(whrplot@data[["Happiness Rank"]],na.rm=TRUE) 

#classify the data to a factor
whrplot@data[["Happy-categories"]] <- cut(whrplot@data[["Happiness Rank"]],
                                                 c(1,25,75,100,125,150,200),
                                                 include.lowest=TRUE )
#rename the categories
levels(whrplot@data[["Happy-categories"]]) <- c('Very High', 'High','High Average','Low Average','Low','Very Low')  

#mapping
mapCountryData(whrplot, 
               nameColumnToPlot='Happy-categories',
               catMethod='categorical',
               mapTitle='Happiness Index from the WHR', 
               colourPalette='palette',
               oceanCol='lightblue',
               missingCountryCol='white',
               borderCol='black')
```


```{r}
url <- "https://raw.githubusercontent.com/Seranne/IntroDSproject/master/Final%20score%20data/CalculatedOurindex.csv"
CalculatedOurindex <- read_csv(url)
CalculatedOurindex$finalindex <- as.numeric(CalculatedOurindex$finalindex )
CalculatedOurindex$region <- as.factor(CalculatedOurindex$region)

```

#Scatter plot showing the distribution of country ranks by region
```{r}
CalculatedOurindex %>%
  ggplot(aes(x = CountryName,
             y = finalindex,
             colour=CalculatedOurindex$region))+ 
  geom_point(size=2, stat="identity") +
  labs(colour = "Regions",
       title = "Scatter plot showing the distribution of country ranks by region", 
       x = "Country", 
       y = "Well-being Index ranking")+ 
  theme_igray()+ 
  theme(axis.text.x = element_text(angle = 90, hjust = 1, size = 2.8)) 

```
#Plot showing the mean regional rank
```{r}
a<- CalculatedOurindex %>%  group_by(region) %>% summarise(fi = mean(finalindex))

a %>%
  ggplot(aes(x = region, 
             y = fi, 
             colour = region))+ 
  geom_point(show.legend = FALSE, size = 7)+ 
  aes(x = fct_reorder(region,
                      fi))+ 
  labs(title = "Plot showing the mean regional rank", 
       x = "Region", 
       y = "Mean Wellbeing Index ranking per region")+ 
  theme_igray()
```
#Scatter plot showing the distribution of country ranks by region
```{r}
CalculatedOurindex %>% 
  ggplot(aes(x = region,
             y = finalindex,
              fill = region))+
  geom_boxplot(show.legend = FALSE)+
  aes(x = fct_reorder(region,finalindex)) + 
  labs(colour = "Regions",
       title = "Scatter plot showing the distribution of country ranks by region", 
       x = "Country", 
       y = "Wellbeing Index ranking") + 
  theme_igray()
```
#Our Happiness Index
```{r}
par(mai=c(0,0,0.2,0),xaxs="i",yaxs="i")

#joining the data to a map
finalindexplot <- joinCountryData2Map(CalculatedOurindex,
                                      joinCode = "NAME",
                                      nameJoinColumn = "CountryName"
)

#creating a user defined colour palette
op <- palette(c('blue','green', 'yellow','orange','red'))

#find quartile breaks
cutVector <- quantile(finalindexplot@data[["finalindex"]],na.rm=TRUE) 

#classify the data to a factor
finalindexplot@data[["Happy-categories"]] <- cut(finalindexplot@data[["finalindex"]],
                                                 c(1,25,75,100,125,150,180),
                                                 include.lowest=TRUE )
#rename the categories
levels(finalindexplot@data[["Happy-categories"]]) <- c('Very High', 'High','High Average','Low Average','Low','Very Low')  

#mapping
mapCountryData(finalindexplot, 
               nameColumnToPlot='Happy-categories',
               catMethod='categorical',
               mapTitle='Happy Highs Wellbeing Index', 
               colourPalette='palette',
               oceanCol='lightblue',
               missingCountryCol='white',
               borderCol='black')
```

#Emission ranks
```{r}
par(mai=c(0,0,0.2,0),xaxs="i",yaxs="i")

#joining the data to a map
finalrank_emission <- joinCountryData2Map(CalculatedOurindex,
                                      joinCode = "NAME",
                                      nameJoinColumn = "CountryName"
)

#creating a user defined colour palette
op <- palette(c('blue','darkgreen','green','yellow','orange', 'red'))

#classify the data to a factor
finalrank_emission@data[["Happy-categories"]] <- cut(finalrank_emission@data[["finalrank_emission"]],
                                                 c(1,27,54,108,135,163,190),
                                                 include.lowest=TRUE )
#rename the categories
levels(finalrank_emission@data[["Happy-categories"]]) <- c('Very Low', 'Low','Low Average','High Average','High','Very High')


#mapping
mapCountryData(finalrank_emission,
               nameColumnToPlot='Happy-categories',
               catMethod='categorical',
               mapTitle='Emission Index', 
               colourPalette='heat',
               oceanCol='lightblue',
               missingCountryCol='white', 
               borderCol='black')

```

#Gender ranks
```{r}
par(mai=c(0,0,0.2,0),xaxs="i",yaxs="i")

#joining the data to a map
finalrank_genplot <- joinCountryData2Map(CalculatedOurindex,
                                      joinCode = "NAME",
                                      nameJoinColumn = "CountryName"
)

#creating a user defined colour palette
op <- palette(c('darkgreen','green','yellow','orange', 'red', 'darkblue'))

#classify the data to a factor
finalrank_genplot@data[["Happy-categories"]] <- cut(finalrank_genplot@data[["finalrank_gen"]],
                                                 c(1,27,54,108,135,163,190),
                                                 include.lowest=TRUE )
#rename the categories
levels(finalrank_genplot@data[["Happy-categories"]]) <- c('Very High', 'High','High Average','Low Average','Low','Very Low')


#mapping
mapCountryData(finalrank_genplot,
               nameColumnToPlot='Happy-categories',
               catMethod='categorical',
               mapTitle='Percentage women in parliament', 
               colourPalette='diverging',
               oceanCol='lightblue',
               missingCountryCol='white', 
               borderCol='black')
```

#Diversity ranks

```{r}
par(mai=c(0,0,0.2,0),xaxs="i",yaxs="i")

#joining the data to a map
finalrankdiv <- joinCountryData2Map(CalculatedOurindex,
                                      joinCode = "NAME",
                                      nameJoinColumn = "CountryName"
)

#creating a user defined colour palette
op <- palette(c('darkgreen','green','yellow','orange', 'red', 'darkblue'))

#classify the data to a factor
finalrankdiv@data[["Happy-categories"]] <- cut(finalrankdiv@data[["finalrank_diversity"]],
                                                 c(1,27,54,108,135,163,190),
                                                 include.lowest=TRUE )
#rename the categories
levels(finalrankdiv@data[["Happy-categories"]]) <- c('Very High', 'High','High Average','Low Average','Low','Very Low')


#mapping
mapCountryData(finalrankdiv,
               nameColumnToPlot='Happy-categories',
               catMethod='categorical',
               mapTitle='Diversity Index', 
               colourPalette='topo',
               oceanCol='lightblue',
               missingCountryCol='white', 
               borderCol='black')
```



